### DISCUSSION TITLE
mkdir: can't create directory '/home/inventree/data/static': Permission denied

### DISCUSSION THREAD

**Discussion by NOP4** [inventree/InvenTree#2463] [Q&A] [answered]
Hello,
I'm trying to install InvenTree but I got these errors in my worker and server, so they don't work.
`mkdir: can't create directory '/home/inventree/data/static': Permission denied`
I'm using a docker-compose file, based on your "server" config. My Traefik and PostgreSQL works fine, just have the error on server and worker.
Here is the docker-compose part for my server and worker:
```
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:stable
        expose:
            - 8000
#        ports:
#            - "8000"
        networks:
            net:
        depends_on:
            - inventree-db
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree-data:/home/inventree/data
        environment:
            - INVENTREE_DEBUG=False
            - INVENTREE_LOG_LEVEL=WARNING
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.inventree_http443.tls=true"
          - "traefik.http.routers.inventree_http443.entrypoints=inventree_http443"
          - "traefik.http.services.inventree_http443.loadbalancer.server.port=8000"
          - "traefik.http.routers.inventree_http443.rule=ClientIP(`192.168.0.0/16`, `::1`)"
          
    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:stable
        command: invoke worker
        networks:
            net:
        depends_on:
            - inventree-db
            - inventree-server
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree-data:/home/inventree/data
        environment:
            - INVENTREE_DEBUG=False
            - INVENTREE_LOG_LEVEL=WARNING
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
        restart: unless-stopped
```
And definition of the volume used:
```
volumes:
  inventree-data:
```
Any idea why I get these errors? When I look at the volume, it is empty. I don't have any problems with my other Docker containers.
Thanks for your help.
