### DISCUSSION TITLE
Deploy Dev Docker behind Traefik proxy

### DISCUSSION THREAD

**Discussion by Bbillyben** [inventree/InvenTree#3469] [Q&A] [answered]
Hi there,

I'm trying to deploy a dev env.  (branch master) behind a traefik proxy, which is already in use for other container on that VM.

The Inventree env. just work fine without traefik handling the request. 
I've done nothing except modifying the docker-compose file, to add labels for traefik :
(after compiling and adding superuser).

The DC file is (with some of my test for traefik) : 
     
```
version: "3.8"

services:
    inventree-dev-db:
        container_name: inventree-dev-db
        image: postgres:13
        expose:
            - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpassword
            - POSTGRES_DB=inventree
        volumes:
          - ./data:/var/lib/postgresql/data
        restart: unless-stopped
		labels:
          - "traefik.enable=false"

    inventree-dev-server:
        container_name: inventree-dev-server
        depends_on:
          - inventree-dev-db
        build:
            context: .
            target: dev
        image: inventree-dev-image
 #       ports:
 #           - 8000:8000
        expose:
		     -8000
        volumes:
            - ./:/home/inventree
        env_file:
            - docker.dev.env
        restart: unless-stopped
		labels:
            - "traefik.enable=true"
            - "traefik.http.routers.stock.rule=Host(`my.site.com`) && PathPrefix(`/stock`)"
            - "traefik.http.routers.stock.entrypoints= http, https"
#            - "traefik.http.routers.stock.middlewares=stock-stripprefix"
#            - "traefik.http.middlewares.stock-stripprefix.stripprefix.prefixes=/stock"
#            - "traefik.http.routers.stock.RawPath='/stock' "
#            - "traefik.http.routers.stock.entrypoints= priv"
#            - "traefik.http.services.stock.loadbalancer.server.port=8000"



    inventree-dev-worker:
        container_name: inventree-dev-worker
        image: inventree-dev-image
        command: invoke worker
        depends_on:
            - inventree-dev-server
        volumes:
            - ./:/home/inventree
        env_file:
            - docker.dev.env
        restart: unless-stopped
		labels:
          - "traefik.enable=false"
```

But I always land on a 504 Gateway Timeout : 
`time="2022-08-04T09:57:59Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 192.168.64.3:8000: i/o timeout"`

Is there something I missed ? or any clue? 

___________________________________________________ 

Docker version 20.10.17, build 100c701
Docker Compose version v2.0.1  (I need that version for other project, but it has worked with latest branch of Inventree)
Debian GNU/Linux 11 (bullseye) / Linux 5.10.0-15-amd64
