### DISCUSSION TITLE
[Plugin] Testing of AppMixin plugins

### DISCUSSION THREAD

**Discussion by wolflu05** [inventree/InvenTree#4123] [Q&A] [answered]
Hello,

I'm currently implementing testing to my bulk-action-plugin in https://github.com/wolflu05/inventree-bulk-plugin/pull/6. I already implemented unit tests for my generation library and now want to extend that to also test my plugins generation of database objects. What would be the recommended way to run Django tests from an plugin as the docs recommend to do, as I have no Django settings module?

> Use the built-in testing functions of django to make sure your code does not cause unwanted behaviour in InvenTree before releasing.

[[Source](https://docs.inventree.org/en/latest/extend/plugins/app/)]

**Comment by matmair** [comment]
@wolflu05 you can add tests as with any other django app. You can then use a github action to run the tests. Mount your repo folder into the latest docker image and run the `manage.py test` command (maybe scoped just to your plugin) to get full e2e tests and check if new releases break anything (you can schedule actions).

**Reply by wolflu05** [reply]
Oh that's a good idea to use the docker image for testing. I'll try that. I already run my tests via gh actions.

**Reply by matmair** [reply]
I am doing this already, if I find time I will amend the docs

**Reply by wolflu05** [reply]
Do you already have a sample/actual plugin repository published which has testing?

**Reply by matmair** [reply]
Nothing that is open-source

**Reply by wolflu05** [reply]
@matmair ~~I already managed to install my plugin via pip into a job container, but now I'm struggling with how to activate the plugin, so that the tests get collected. Is there any option to add some env for activated plugins, or is there a curl command with which I can active my plugin and allow the app mixing? How do you handle this?~~
**EDIT:** Seems like it's not necessary to activate the plugin, tests will run no matter if activated.

**Reply by matmair** [reply]
@wolflu05 I normally mount the plugin directory into the container, pass it to the config as a plugin dir and then activate plugin testing mode by setting `PLUGIN_TESTING` and `PLUGIN_TESTING_SETUP` to true.

**Reply by matmair** [reply]
A good example how you can test install process would be this one: https://github.com/inventree/InvenTree/blob/a69c524cd83401c503b5feae240583d69af859f6/InvenTree/plugin/test_plugin.py#L244-L256

**Reply by wolflu05** [reply]
My issue now is how to get coverage reports working? If I do `coverage run InvenTree/manage.py test inventree_bulk.tests.integration --keepdb` my tests definitely run, but the coverage report doesn't contain any information about my files.

**Reply by wolflu05** [reply]
> A good example how you can test install process would be this one:

Why would I test the install process, isn't that something inventree core should do?

My job currently looks like this, but the coverage report doesn't contain my plugin files.

<details>

```yml
tests-integration:
    name: 🧪 Integration tests
    runs-on: ubuntu-latest

    container:
      image: inventree/inventree:stable
      env:
        INVENTREE_DB_ENGINE: postgresql
        INVENTREE_DB_NAME: inventree
        INVENTREE_DB_HOST: db
        INVENTREE_DB_PORT: 5432
        INVENTREE_DB_USER: inventree
        INVENTREE_DB_PASSWORD: inventree
        INVENTREE_PLUGINS_ENABLED: True

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: inventree
          POSTGRES_PASSWORD: inventree
          POSTGRES_DB: inventree

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup inventree
        run: |
          cd /home/inventree
          inv update

      - name: Setup inventree_bulk_plugin
        run: |
          cd /home/inventree
          pip install -e $GITHUB_WORKSPACE
          pip install coverage==6.0 # https://github.com/nedbat/coveragepy/issues/1150

      - name: Run tests
        run: |
          cd /home/inventree
          coverage run InvenTree/manage.py test inventree_bulk.tests.integration
          coverage report
```

</details>
