### DISCUSSION TITLE
Beginner: Scripted Bare Metal, move from SQLite to PostgreSQL

### DISCUSSION THREAD

**Discussion by method1020** [inventree/InvenTree#4227] [Q&A]
I have a VM running (Ubuntu install) a fresh InvenTree install from the 'bare metal' script provided in the docs. **How would I go about moving this to a better suited database such as PostgreSQL?** 

I performed the PostgreSQL install:

Install POSTGRESQL:
```bash
sudo apt-get install postgresql postgresql-contrib libpq-dev
sudo service postgresql start
sudo -u postgres psql
```
and setup the user/database as described in the docs:

```postgresql
create database inventree;
create user myuser with encrypted password 'mypass';
grant all privileges on database inventree to myuser;
\q
```
(with changes to myuser and mypass)

The next steps i'm stuck on. it looks like i need to install psycopg2 pgcli via pip, do i do this in a virtual environment? Did the scripted install make a virtual environment?

I did also change the config file from

```yaml
  ENGINE: sqlite3
  NAME: '/opt/inventree/data/database.sqlite3'
  USER: sampleuser
  PASSWORD: samplepassword
  HOST: samplehost
  PORT: sampleport
```
to

```yaml
 ENGINE: postgresql
 NAME: inventree
 USER: inventree
 PASSWORD: inventree_password
 HOST: 'localhost'
 PORT: '5432'
```

(with changes to name/user/password where appropriate) 

Sorry I'm learning a lot here as I go.
