### DISCUSSION TITLE
First time trying to install plugins. Web interface option not available.

### DISCUSSION THREAD

**Discussion by Benjamin0001** [inventree/InvenTree#4517] [Q&A]
I'm trying to install the [https://github.com/wolflu05/inventree-bulk-plugin](https://github.com/wolflu05/inventree-bulk-plugin)
Why do I get this on the settings page?
`External plugins are not enabled for this InvenTree installation`
I edited the .env and config.yaml to True after reading [this](https://docs.inventree.org/en/latest/start/config/#plugin-options).

I'm trying to figure out PIP. What to I put in the plugins.txt?

**Comment by SchrodingersGat** [comment]
Did you completely restart the server after making changes to your environment files?

**Reply by Benjamin0001** [reply]
a few times, I think. I just press the restart option in the docker desktop app. or also did stop and then play too. lol

**Reply by Benjamin0001** [reply]
This is what I put in my plugins.txt
```
# InvenTree Plugins (uses PIP framework to install)
git+https://github.com/wolflu05/inventree-bulk-plugin.git
```
but that doesn't seem to work

**Reply by SchrodingersGat** [reply]
@wolflu05 any thoughts on this one?

**Reply by Benjamin0001** [reply]
a friend helped me get the add plugins button working but he couldn't get the bulk plugin to work on his machine and told me to not try.
He also pointed out that I can import locations via .csv and that made me internally "forehead-desk" pretty hard. lol. So i guess that solves my more core issue of how to create over 100+ locations. Hopefully I wont screw that up XD

**Reply by wolflu05** [reply]
> @wolflu05 any thoughts on this one?

Sorry, no idea, the plugin definitely worked with 0.9.3, haven't tested it on newer versions because I'm currently limited in time. Maybe something of the plugin architecture broke 🤔 . If so I can only fix this in a few months.

**Reply by matmair** [reply]
@Benjamin0001 what was the solution to get plugins to work?
The bulk plugin should just work, I have it running on my (stable) production setup.

**Reply by Benjamin0001** [reply]
I'll have to ask my friend exactly what we did. I am on the production version inside of Docker on Windows 10. 
I think we rebuilt the database. I remember that one of the commands had an "invoke update" on the end of it. Somehow after rebuilding the database my one test part was still there. Hopefully in a few hours he can provide a better answer. I'll let him know that you have the plugin working.

**Reply by dvigne** [reply]
> > @wolflu05 any thoughts on this one?
> 
> Sorry, no idea, the plugin definitely worked with 0.9.3, haven't tested it on newer versions because I'm currently limited in time. Maybe something of the plugin architecture broke thinking . If so I can only fix this in a few months.

Thats interesting, I had to rollback my server before the plugin even popped up and started registering. I tried 0.9.0, but Inventree just kept reporting it as unavailable. I figured out I had to rollback after the plugin failed to load or even show up in the logs on v 0.10.0. I'll have to see if 0.9.3 gets it to work properly.

**Reply by wolflu05** [reply]
Actually I realized, that 0.9.3 was never released, v0.10.0 was released before. And note that you need at min 0.9.1 as there was a [bug](https://github.com/wolflu05/inventree-bulk-plugin/blob/dev/inventree_bulk_plugin/InvenTreeBulkPlugin.py#L30) with invoke update before

**Reply by dvigne** [reply]
Gotcha, I tried 0.9.0 and ran into that invoke update bug you mentioned. I managed to work around the bug and get invoke update to run on 0.9.0, but I will try 0.9.1 and see if that makes a difference.

**Comment by dvigne** [comment]
@matmair Hello,

I am the friend that @Benjamin0001 was mentioning earlier about. In order to get the plugins working inside the docker container, we had to set `INVENTREE_PLUGINS_ENABLED` environment variable to `True` and I personally chose to break the plugins into their own separate directory and mount them as a volume by adding the following lines to my `.env` file and my `docker-compose.yml` file.

### .env
```
# Custom plugins directory
INVENTREE_PLUGIN_DIR=/plugins
INVENTREE_PLUGIN_EXT_DIR=/home/dvigne/Documents/GitHub/docker-compose/inventree/plugins
```

### docker-compose.yml
```
    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        expose:
            - 8000
        depends_on:
            - inventree-db
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree_data:/home/inventree/data
            - inventree_plugins:${INVENTREE_PLUGIN_DIR} # Additional mounted volume for Plugins
        restart: unless-stopped
volumes:
    # Persistent data, stored external to the container(s)
    inventree_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            device: ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}
    inventree_plugins:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            device: ${INVENTREE_PLUGIN_EXT_DIR:?You must specify the 'INVENTREE_PLUGIN_EXT_DIR' variable in the .env file!}
```
After making these edits, I ran a `docker compose run inventree-server invoke update` and the plugins directory was bootstrapped and available.

@matmair what version of Inventree are you running?
