### DISCUSSION TITLE
Simple page changes

### DISCUSSION THREAD

**Discussion by SeanAustin** [inventree/InvenTree#5217] [Q&A] [answered]
I installed Inventree with the installer on a Linux virtual machine running ubuntu. I have not made any changes to the server, it currently starts when the virtual machine boots. 

I have a basic understanding of python and have been trying to make some simple changes but have hit a wall. I just want to customize the site to show my companies info. I have edited the config file by uncommenting the customization options. The only thing I changed was adding the location of the logo file. I have restarted my server but I do not see any of the changes. Is there something else I need to restart to push the change? I also see that I can make the changes with an environment variable but have not been able to figure out where the environment variables should be placed. 

Any help would be greatly appreciated.

**Comment by SchrodingersGat** [comment]
- What have you set the custom logo path to?
- is there a custom.logo located at that path?

**Comment by SeanAustin** [comment]
I placed a custom logo in the same directory as the config, etc/inventree, the file is named logo. 

This is the code that i changed, 

```python
# Customization options
# Add custom messages to the login page or main interface navbar or exchange the logo
# Use environment variable INVENTREE_CUSTOMIZE or INVENTREE_CUSTOM_LOGO
customize:
login_message: InvenTree demo instance - <a href='https://docs.inventree.org/en/latest/demo/'> Click here for login details</a>
#   navbar_message: <h6>InvenTree demo mode <a href='https://docs.inventree.org/en/latest/demo/'><span class='fas fa-info-circle'></span></a></h6>
logo: /etc/inventree/logo.png
#   splash: splash_screen.jpg
#   hide_admin_link: true
#   hide_password_reset: true
``` 

None of these changes have appeared even after restarting the server. I am not sure if I need to run a command to get the server to look for these changes. Currently the server starts when I start my VM. I am not sure if any extra configuration is needed to tell the server to look for the config file.

**Reply by wolflu05** [reply, marked as answer]
You need to pay attention to the correct indentation. `login_message` and the other options are sub options of `customize`. In yml syntax every space before a key matters. You would need to have the following (two spaces or one tab before each key):
```yml
customize:
  login_message: InvenTree demo instance - <a href='https://inventree.readthedocs.io/en/latest/demo/'> Click here for login details</a>
#   navbar_message: <h6>InvenTree demo mode <a href='https://inventree.readthedocs.io/en/latest/demo/'><span class='fas fa-info-circle'></span></a></h6>
  logo: logo.png
#   hide_admin_link: true
#   hide_password_reset: true
```
