### DISCUSSION TITLE
Record how to install InvenTree in Chinese Mainland by using Ubuntu 20.04 Server/Desktop+Docker.

### DISCUSSION THREAD

**Discussion by zly20129** [inventree/InvenTree#7716] [Show and tell]
- 最重要的基础准备（假设运行V2RayN的PC的IP地址为1.1.1.13@局域网）：
1.准备V2RayN（运行在哪个系统上不重要，但必须在局域网或公网环境下）；
2.准备V2RayN的免费节点（这部分可以去油管找，很多白嫖的节点）；
3.在V2RayN中测试连接延迟，找一个真连接延迟低的设置为活动节点，并在V2RayN的设置中开启局域网共享。
注：此时，需要在局域网中的其他设备设置代理服务器，V2RayN默认的端口一般是10809@http，那么就设置1.1.1.13:10809，测试能否访问国外网站，如果可以，那么可以继续接下来的操作。

- 环境准备（假设运行InvenTree的系统的IP地址为1.1.1.12@局域网）：
1.需要一个Ubuntu系统，20.04和22.04都可以，我采用的是VMware虚拟机的形式，方便移植；
2.更新系统软件包`sudo apt update`；
3.（可选）安装SSH服务端`sudo apt-get install openssh-server`；
注：如果选中此步骤，则完成后需要验证SSH是否可以连接！
4.将当前的IP地址在路由器中设置为静态IP！
注：静态IP设置至关重要！

- 安装Docker：
1.`sudo apt update`；
2.`sudo apt install apt-transport-https ca-certificates curl software-properties-common`；
3.`sudo -i`；
4.用镜像源添加公钥`curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-ce.gpg`；
5.验证公钥是否添加成功`sudo apt-key fingerprint 0EBFCD88`；
6.`sudo add-apt-repository "deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"`；
7.`sudo apt update`；
8.`sudo apt install docker-ce docker-ce-cli containerd.io`；
9.检查是否存在`/etc/docker`文件夹，如果没有，则用`sudo mkdir /etc/docker`创建它；
10.换源，编辑此文件`sudo nano /etc/docker/daemon.json`，而后将以下内容填入并保存；
```
{
"registry-mirrors": [
        "https://registry.docker-cn.com",
        "https://docker.mirrors.ustc.edu.cn",
        "https://hub-mirror.c.163.com",
        "https://mirror.baidubce.com",
        "https://ccr.ccs.tencentyun.com"
    ]
}
```

11.`sudo systemctl daemon-reload`；
12.`sudo systemctl restart docker`；
13.检查安装是否成功`sudo docker run hello-world`；
注：只有输出正确的结果，说明安装成功，才可以继续后续步骤！
14.`sudo docker images`；
15.这里要注意用户名的替换`sudo usermod -aG docker 你自己的用户名`；
16.切换用户，一样要替换用户名`su - 你自己的用户名`；
17.验证下权限配置，没有报错才是对的`docker images`；
18.设置开机自启`sudo systemctl enable docker`。

- 安装InvenTree：
1.为Dockerd创建配置文件夹`sudo mkdir -p /etc/systemd/system/docker.service.d`；
2.准备设置代理，执行`sudo nano  /etc/systemd/system/docker.service.d/http-proxy.conf`，并将以下内容填入文件而后保存；
```
[Service]
Environment="HTTP_PROXY=http://1.1.1.13:10809/"
Environment="HTTPS_PROXY=http://1.1.1.13:10809/"
```

3.`sudo systemctl daemon-reload`；
4.`sudo systemctl restart docker`；
5.`cd ~`
6.将仓库克隆到本地，如果克隆Github失败，可以尝试将Github上的仓库Fork到Gitee，然后再克隆，比如`git clone https://gitee.com/zly20129/inventree.git`；
注：我Fork的这个仓库并不会持续拉取同步！
7.`cd inventree`；
8.按自己需求切换分支，比如`git checkout stable`；
9.`cd ~/inventree/contrib/container`；
10.使用`nano .env`配置环境变量，具体功能可以参见官方文档，我这里写的是我自己的功能模板；
```
# InvenTree environment variables for docker compose deployment

# Specify the location of the external data volume
# By default, placed in local directory 'inventree-data'
INVENTREE_EXT_VOLUME=/home/你自己的用户名/inventree-data

# Default web port for the InvenTree server
INVENTREE_WEB_PORT=准备用IP访问的WEB端口，比如HTTP的80端口

# Ensure debug is false for a production setup
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING

# InvenTree admin account details
# Un-comment (and complete) these lines to auto-create an admin acount
INVENTREE_ADMIN_USER=自定义管理员用户名
INVENTREE_ADMIN_PASSWORD=自定义管理员密码
INVENTREE_ADMIN_EMAIL=自定义邮箱

# Database configuration options
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432

# Database credentials - These should be changed from the default values!
INVENTREE_DB_USER=pguser
INVENTREE_DB_PASSWORD=自定义数据库密码

# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
#INVENTREE_CACHE_HOST=inventree-cache
#INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=True

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=True

# Image tag that should be used
INVENTREE_TAG=stable

# Site URL - update this to match your host
#INVENTREE_SITE_URL="http://inventree.localhost"这一行没有用，可以删掉
INVENTREE_SITE_URL="http://1.1.1.12"这里必须填和你机器静态IP一样的IP地址，否则只会看到一片白色的屏幕，无法访问

# Base currency code (or use env var INVENTREE_BASE_CURRENCY)
INVENTREE_BASE_CURRENCY=CNY钱币，按国家设置，中国大陆设置CNY

COMPOSE_PROJECT_NAME=inventree

```

注：以上文件仅供参考，里面所有的汉字要么被你自己的设定替代，要么删掉，整个文件最终不要留有除注释以外的一个汉字！！！
11.按环境设定创建文件夹`mkdir /home/你自己的用户名/inventree-data`；
12.用手动指定代理的方式安装`docker compose run --rm -e HTTP_PROXY=1.1.1.13:10809 -e HTTPS_PROXY=1.1.1.13:10809 inventree-server invoke update`；
注：如果这一步发生错误，或者网络波动而中断，就多试几次，有代理总有一次会成功，如果多次尝试也不成功那就考虑换代理节点！
13.（可选）安装好后，把管理员账号密码从`.env`文件里删除，保证安全性；
14.准备开始运行`docker compose up -d`；
注：这一步可能也会受网络波动影响，多试几次，总会有一次成功，不行就换节点！！！
15.再次运行`docker compose up -d`，如果列出的几个项全都是Running状态，那么说明安装成功，否则如果有Started则说明安装有问题，要么卸载重装，要么重装系统从头开始；
注：我在安装过程中，有一次先安装了nginx，它占用了80端口，这使得inventree-proxy服务器安装失败，即使我卸载了nginx并重装了inventree，inventree-proxy依旧显示started状态，无法网络访问，最终重装Ubuntu系统并从头开始得以解决。
16.清除代理，执行`sudo nano  /etc/systemd/system/docker.service.d/http-proxy.conf`，并将文件中的内容全部注释掉，或者删除，最后保存，比如下述结果；
```
#[Service]
#Environment="HTTP_PROXY=http://1.1.1.13:10809/"
#Environment="HTTPS_PROXY=http://1.1.1.13:10809/"
```

17.`sudo systemctl daemon-reload`；
18.`sudo systemctl restart docker`；
19.使用浏览器测试能否打开Inventree网络页面，如果能打开说明安装成功，打不开说明某步出现问题，可自行排查、重装或者在Github上提issues。

- 更新InvenTree：
1.设置代理，执行`sudo nano  /etc/systemd/system/docker.service.d/http-proxy.conf`，并将以下内容填入文件而后保存；
```
[Service]
Environment="HTTP_PROXY=http://1.1.1.13:10809/"
Environment="HTTPS_PROXY=http://1.1.1.13:10809/"
```

2.`sudo systemctl daemon-reload`；
3.`sudo systemctl restart docker`；
4.`docker compose down`；
5.`docker compose pull`；
6.清除代理，执行`sudo nano  /etc/systemd/system/docker.service.d/http-proxy.conf`，并将文件中的内容全部注释掉，或者删除，最后保存，比如下述结果；
```
#[Service]
#Environment="HTTP_PROXY=http://1.1.1.13:10809/"
#Environment="HTTPS_PROXY=http://1.1.1.13:10809/"
```

7.`sudo systemctl daemon-reload`；
8.`sudo systemctl restart docker`；
9.`cd ~/inventree/contrib/container`；
10.打开文件`nano docker-conpose.conf`并找到inventree-server:一段，以下是原文件内容；
```
version: "3.8"

# Docker compose recipe for a production-ready InvenTree setup, with the following containers:
# - PostgreSQL as the database backend
# - gunicorn as the InvenTree web server
# - django-q as the InvenTree background worker process
# - Caddy as a reverse proxy
# - redis as the cache manager (optional, disabled by default)

# ---------------------
# READ BEFORE STARTING!
# ---------------------

# -----------------------------
# Setting environment variables
# -----------------------------
# Shared environment variables should be stored in the .env file
# Changes made to this file are reflected across all containers!
#
# IMPORTANT NOTE:
# You should not have to change *anything* within this docker-compose.yml file!
# Instead, make any changes in the .env file!

# ------------------------
# InvenTree Image Versions
# ------------------------
# By default, this docker-compose script targets the STABLE version of InvenTree,
# image: inventree/inventree:stable
#
# To run the LATEST (development) version of InvenTree,
# change the INVENTREE_TAG variable (in the .env file) to "latest"
#
# Alternatively, you could target a specific tagged release version with (for example):
# INVENTREE_TAG=0.7.5
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    # only runs under the "redis" profile : https://docs.docker.com/compose/profiles/
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        depends_on:
            - inventree-db
        profiles:
            - redis
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z

    # alternative: run nginx as reverse proxy
    # inventree-proxy:
    #     container_name: inventree-proxy
    #     image: nginx:stable
    #     restart: always
    #     depends_on:
    #         - inventree-server
    #     ports:
    #         - ${INVENTREE_WEB_PORT:-80}:80
    #         - 443:443
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
    #         - ${INVENTREE_EXT_VOLUME}:/var/www:z
```

11. 在这一段内添加如下内容并保存：
```
environment:
- http_proxy=1.1.1.13:10809
- https_proxy=1.1.1.13:10809
```
最终文件如下；
```
version: "3.8"

# Docker compose recipe for a production-ready InvenTree setup, with the following containers:
# - PostgreSQL as the database backend
# - gunicorn as the InvenTree web server
# - django-q as the InvenTree background worker process
# - Caddy as a reverse proxy
# - redis as the cache manager (optional, disabled by default)

# ---------------------
# READ BEFORE STARTING!
# ---------------------

# -----------------------------
# Setting environment variables
# -----------------------------
# Shared environment variables should be stored in the .env file
# Changes made to this file are reflected across all containers!
#
# IMPORTANT NOTE:
# You should not have to change *anything* within this docker-compose.yml file!
# Instead, make any changes in the .env file!

# ------------------------
# InvenTree Image Versions
# ------------------------
# By default, this docker-compose script targets the STABLE version of InvenTree,
# image: inventree/inventree:stable
#
# To run the LATEST (development) version of InvenTree,
# change the INVENTREE_TAG variable (in the .env file) to "latest"
#
# Alternatively, you could target a specific tagged release version with (for example):
# INVENTREE_TAG=0.7.5
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    # only runs under the "redis" profile : https://docs.docker.com/compose/profiles/
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        depends_on:
            - inventree-db
        profiles:
            - redis
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        environment:
            - http_proxy=1.1.1.13:10809
            - https_proxy=1.1.1.13:10809
        expose:
            - 8000
        depends_on:
            - inventree-db
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z

    # alternative: run nginx as reverse proxy
    # inventree-proxy:
    #     container_name: inventree-proxy
    #     image: nginx:stable
    #     restart: always
    #     depends_on:
    #         - inventree-server
    #     ports:
    #         - ${INVENTREE_WEB_PORT:-80}:80
    #         - 443:443
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
    #         - ${INVENTREE_EXT_VOLUME}:/var/www:z

```

12. `docker compose up -d`；
13. `docker compose exec inventree-server invoke update`；
14. 将刚才添加的代理内容从文件中删除，恢复如第10步所示的文件初始内容；
15. 重启服务器`docker compose up -d`或者系统重启；
16. 恭喜你，更新成功！

到此，你的InvenTree服务器已经可以正常工作了，快乐的体验吧！
附言：截至发稿，我还没成功的用installer.sh安装成功过，即使配置了代理和pip换源也没有成功过，不知道哪里有错误，所以推荐还是用Docker安装吧。
