### ISSUE TITLE
Docker: add docker compose secret key support

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1456]
Docker compose supports secrets.  
```
secrets:
  postgres_user:
    file: ./data/secrets/postgres_user
  postgres_password:
    file: ./data/secrets/postgres_password
```

The standard postgres container can use them like so:

```
db:
 image: postgres
 container_name: db
 networks:
   - db
 expose:
   - 5432/tcp
 secrets:
   - postgres_password
   - postgres_user
 environment:
   - PGDATA=/var/lib/postgresql/data/pgdb
   - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
   - POSTGRES_USER_FILE=/run/secrets/postgres_user
```

This allows me to reuse the same secret easily as well as changing the secret for both sides of the connection in one place.
