### ISSUE TITLE
Docker: allow user to use the official nginx server

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1457]
I would recommend in the docker_compose example, to rather than deploy a custom nginx container, just specify a config file in the directions and allow the user to mount it inside the docker container.

This will require less infrastructure overhead for you to maintain your own custom docker container, when all the users really need is the nginx config.

**Comment by rcludwick** [comment]
```
server {

    listen 80;

    location / {
        proxy_pass http://inventree;
```

As a docker user I might need to change the port as well as the name of the server (since something else may be running on 80 in the same box/network).  Right now I have mine named "inventree-web", but this nginx file wouldn't work.

**Comment by SchrodingersGat** [comment]
Excellent suggestions. I was not sure if that was possible with the nginx image but if so, that's much better. 

Can the conf file support environment variables?

**Comment by rcludwick** [comment]
Yes.... through an env file.  Or though secrets.

**Comment by rcludwick** [comment]
Okay ... this is what I got working tonight.  @SchrodingersGat Tell me what you think:

nginx.conf:  (Note: proxy_pass needs to use whatever the container name and port is in docker, in this case I use "inventree-web")
```
server {
    listen 80;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_pass http://inventree-web:8080;
    }

    location /static/ {
        root /var/inventree/www;
        autoindex on;
    }

}
```

Then my docker-compose.yml looks like this: 

```
  inventree-web:
    container_name: inventree-web
    image: inventree/inventree:latest
    networks:
      - proxy
      - db
    expose:
      - 8080
    depends_on:
      - db
    volumes:
      - ./data/inventree/data:/home/inventree/data
      - ./data/inventree/static:/home/inventree/static
    environment:
      - INVENTREE_DB_ENGINE=postgresql
      - INVENTREE_DB_NAME=inventree
      - INVENTREE_DB_USER=pguser
      - INVENTREE_DB_PASSWORD=pgpasswd
      - INVENTREE_DB_PORT=5432
      - INVENTREE_DB_HOST=db
    restart: unless-stopped

  inventree-worker:
    container_name: inventree-worker
    image: inventree/inventree:latest
    entrypoint: ./start_worker.sh
    networks:
      - proxy
      - db
    depends_on:
      - db
      - inventree-web
    volumes:
      - ./data/inventree/data:/home/inventree/data
      - ./data/inventree/static:/home/inventree/static
    environment:
      - INVENTREE_DB_ENGINE=postgresql
      - INVENTREE_DB_NAME=inventree
      - INVENTREE_DB_USER=pguser
      - INVENTREE_DB_PASSWORD=pgpasswd
      - INVENTREE_DB_PORT=5432
      - INVENTREE_DB_HOST=db
    restart: unless-stopped

  inventree-proxy:
    container_name: inventree-proxy
    image: nginx
    networks:
      - proxy
    depends_on:
      - db
      - inventree-web
    expose:
      - 80/tcp
    volumes:
      - ./data/inventree/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/inventree/static:/var/inventree/www/static:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
```
