### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by bgrant85** [inventree/InvenTree#1942]
I have a couple easy questions;
1) Is there an easy way to export a BOM that can be used for ordering.  It would need to include supplier, supplier part number, link, stock qty and required qty.  It would need to be in csv or xlsx format so I can manipulate it.  For example, order by supplier so I can build an order for each supplier.  The bom that I exported did not have any supplier info.

2) Is there a way to easily update the version of inventree to a particular version?   To do my last update I used the following commands:
~/src/docker$ sudo docker-compose down
~/src/docker$ sudo docker-compose pull
~/src/docker$ sudo docker-compose up -d
What I ended up with is version 0.5.0 pre.  What I wanted was the lastest release (0.4.5)

3) Harder question:  I have bunch (100 or so) parts in my database with no supplier part attached.  The supplier part number is the same as my part number.  I'd like to create a CSV file (by exporting to xlsx, manipulating and adding columns etc) that I can then import to add supplier (which already exists) and supplier part (which does not yet exist) to each of the associated parts.  Is this doable or will it require significant programming effort to do this type of import?

**Comment by matmair** [comment]
Hi there @bgrant85!

1. The current workflow for ordering is to either build up the orders in InvenTree as POs and the export the POs or use the BOM exporter
![grafik](https://user-images.githubusercontent.com/66015116/128934695-7672cd9b-a363-4bd1-87ae-cbfb1fe8f3e9.png)

2. I am not that used to docker but @42CrMo4 or @SchrodingersGat maybe can help with this

3. I do not think we provide this option at the moment. Would be quite easy to do if you are somewhat familiar with phyton - we provide a interface-module for stuff like this ([this section](https://inventree.readthedocs.io/en/latest/extend/python/#adding-manufacturers-and-supplier) shows how to add a supplier part).

**Comment by SchrodingersGat** [comment]
2. Specific version in docker

This one is pretty simple actually. In your `docker-compose.yml` file, change:

```yaml
    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:latest
```

to 

```yaml
    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:0.4.5
```

(or substitute a different particular version instead of 0.4.5

3. SupplierPart import

A couple of options here. You could use the [python bindings](https://github.com/inventree/inventree-python) and write a script to bring this data in.

Or you could import the SupplierPart information using the admin interface:

![image](https://user-images.githubusercontent.com/10080325/128944870-967d7ccc-18d3-48dc-980e-1db2a805f22c.png)

If you used the admin import approach, you would need to map each SupplierPart to a Part **id** value in the file (e.g. csv of xlsx) before import)
