### ISSUE TITLE
Missing required database configuration value ENGINE running invoke update

### ISSUE THREAD

**Issue by Hack4Life** [inventree/InvenTree#3900]
Hi,
I am new to Inventiere and trying to setup the tool via Docker and an .env file (File contents below). 
However when I run `docker-compose run inventree-server invoke update` I get the following error: 

```
Running InvenTree database migrations...
========================================
Error: Missing required database configuration value ENGINE2022-11-05 13:02:26,707 ERROR Missing required database configuration value ENGINE

ERROR: 255
```

I have double checked my .env file but I have defined my DB_ENGINE as described: 
`INVENTREE_DB_ENGINE=postgresql`

This is my complete .env file content: 
```
INVENTREE_EXT_VOLUME=/home/inventree/data
INVENTREE_WEB_PORT=1337
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING
INVENTREE_ADMIN_USER=AdminUser1
INVENTREE_ADMIN_PASSWORD=password
INVENTREE_ADMIN_EMAIL=mail@test.com
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432
INVENTREE_DB_USER=at_ba_it-admin
INVENTREE_DB_PASSWORD=dbpassword
INVENTREE_PLUGINS_ENABLED=False
INVENTREE_TAG=stable
COMPOSE_PROJECT_NAME=inventree-production
```

And this is my docker-compose.yml file:
```
version: "3.8"

services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        container_name: inventree-db
        image: postgres:13
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD}
            - POSTGRES_DB=${INVENTREE_DB_NAME}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - inventree_data:/var/lib/postgresql/data/
        restart: unless-stopped

    # redis acts as database cache manager
    # only runs under the "redis" profile : https://docs.docker.com/compose/profiles/
    inventree-cache:
        container_name: inventree-cache
        image: redis:7.0
        depends_on:
            - inventree-db
        profiles:
            - redis
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        expose:
            - 8336
        depends_on:
            - inventree-db
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree_data:/home/inventree/data
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        container_name: inventree-worker
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        command: invoke worker
        depends_on:
            - inventree-server
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree_data:/home/inventree/data
        restart: unless-stopped

volumes:
    # Persistent data, stored external to the container(s)
    inventree_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            device: ${INVENTREE_EXT_VOLUME}

networks:
  default:
    name: nginx-reverseproxy_default
    external: true
```

The setup is almost the same as described in the docs besides that I am using my own network where I have my nginx reverse proxy running for all my docker applications. 

Can someone help me get Inventiere up&running or give me a hint, what's the problem with the Engine? 

BR from Austria,
Fabian
