### ISSUE TITLE
OAuth login broken with Microsoft Graph due to failing sso_check_provider

### ISSUE THREAD

**Issue by hvraven** [inventree/InvenTree#5330]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Since the upgrade from 0.10 first to 0.11, now 0.12.1 the previously working OAuth Login via Microsoft Graph is broken on our installation. My primary problem is the lack of any output from inventree on whats not working. When acccessing the login URL I get the error message, stating "The selected SSO provider is invalid, or has not been correctly configured", but no information in the error log or on the log in the container. I increased the log level to DEBUG, but that added primarily access logs.

Is there any way to get more log information out of Inventree and figure out why it doesn't like the configuration. I verified that all the required entries are (still) there.

### Steps to Reproduce
* Install inventree, configuring basic setup incl. e-mail
* Configure backends & middlewares. Section of my `config.yaml`:
```yaml
authentication_backends:
  - 'django.contrib.auth.backends.ModelBackend'
  - 'allauth.account.auth_backends.AuthenticationBackend'

#  Custom middleware, sometimes needed alongside an authentication backend change.
middleware:
  - 'django.middleware.security.SecurityMiddleware'
  - 'x_forwarded_for.middleware.XForwardedForMiddleware'
  - 'django.contrib.sessions.middleware.SessionMiddleware'
  - 'django.middleware.locale.LocaleMiddleware'
  - 'django.middleware.common.CommonMiddleware'
  - 'django.middleware.csrf.CsrfViewMiddleware'
  - 'corsheaders.middleware.CorsMiddleware'
  - 'django.contrib.auth.middleware.AuthenticationMiddleware'
  - 'InvenTree.middleware.InvenTreeRemoteUserMiddleware'
  - 'django_otp.middleware.OTPMiddleware'
  - 'django.contrib.messages.middleware.MessageMiddleware'
  - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  - 'InvenTree.middleware.AuthRequiredMiddleware'
  - 'maintenance_mode.middleware.MaintenanceModeMiddleware'
  - 'InvenTree.middleware.InvenTreeExceptionProcessor'

# Add SSO login-backends (see examples below)
social_backends:
  - 'allauth.socialaccount.providers.microsoft'

# Add specific settings for social account providers (if required)
social_providers:
  microsoft:
    TENANT: 'uuid-of-my-tenant'
```
* Create a new social app in the admin interface, selecting the sole provider "Microsoft Graph", specifying client & secret (can be anything at this stage) and enable for the default site
* In inventree settings go to auth and enable SSO
### Expected behaviour

Login works or at least some output for debugging can be generated

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

0.12.1

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.
