### ISSUE TITLE
Microsoft SSO fails with "Sign up is currently closed."

### ISSUE THREAD

**Issue by mittkkoo** [inventree/InvenTree#5866]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I configured SSO with single-tenant Azure AD (Microsoft) as described [in the docs](https://docs.inventree.org/en/stable/settings/SSO/#enable-sso-settings)

This is in config.yaml:
```
# Add SSO login-backends (see examples below)
social_backends:
  - 'allauth.socialaccount.providers.microsoft'

social_providers:
  microsoft:
    TENANT: 'copied from https://entra.microsoft.com/#view/Microsoft_AAD_IAM/TenantOverview.ReactView'
``` 

This is the Settings / Login screen:

![image](https://github.com/inventree/InvenTree/assets/76665232/e2bcd40e-56f4-46a7-8484-e2a488922fe4)

The Button Microsoft Graph appers on the login screen and the Microsoft process is started, but afterwards inventree reports "Sign up is currently closed."

### Steps to Reproduce

1. Setup Microsoft SSO as in the docs
2. Add a social application through the UI
3. Change Settings / Login as in the screenshot

### Expected behaviour

Expect SSO to work.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff8
Commit Date: None
Commit Branch: stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Can you share a (redacted) screenshot of the SSO application you setup in the admin interface? Ensure that the name of the application is `microsoft` (case sensitive)

**Comment by mittkkoo** [comment]
Yes, microsoft
![image](https://github.com/inventree/InvenTree/assets/76665232/29fc730e-f8db-48c7-afb9-d8e1aed463ca)
Client ID is from https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade -> "Application (client) ID"
Secret key from the same place -> Client credentials -> Client secrets -> Value

**Comment by SchrodingersGat** [comment]
I am assuming that the `tenant` value in your config file is *not* actually the literal value that you pasted in your example:

```
social_providers:
  microsoft:
    TENANT: 'copied from https://entra.microsoft.com/#view/Microsoft_AAD_IAM/TenantOverview.ReactView'
```

**Comment by mittkkoo** [comment]
I discoverd [this approach to setup the application](https://stackoverflow.com/a/77314718/21972361), which differs from mine above. The setting is like this:
![image](https://github.com/inventree/InvenTree/assets/76665232/820a9f91-3f30-41b4-aa86-dcf7fc0cc01a)

With this again the authentication process of Microsoft is started and afterwards inventree reports a different error: 
_"Account Login Failure
Contact your system administrator for further information."_

**Comment by SchrodingersGat** [comment]
Is your InvenTree setup behind a proxy? The headers for the request must be forwarded correctly, so that it is `https://inventree.domain.com...` and not `https://xxx.xxx.xxx.xxx/...`

**Comment by SchrodingersGat** [comment]
Additionally, are there any error logs available in the database after the login attempt? Or any log messages from the InvenTree server instance?

**Comment by SchrodingersGat** [comment]
You also might want to look into the value you have put into `TENANT`.

According to the [django-allauth docs](https://docs.allauth.org/en/latest/socialaccount/providers/microsoft.html) and [our docs](https://docs.inventree.org/en/stable/settings/SSO/?h=sso#configuration-file) it looks like it should be set to `organizations` (potentially)

**Comment by mittkkoo** [comment]
The request headers are all with the domain as far as I can see with the browser. In error reports in the UI there is nothing, nginx reports no errors also. As far as I could understand from config.yaml and settings.py I can increase the log level to see more logs, but still didn't try that. 
In config.yaml I also tried with organizations, but no difference. The docs of allauth are not helping much. Django is 3.2.19 and allauth 0.54. Putting all settings in settings.py seems not to work. I tried, but inventree won't run afterwards.

**Comment by matmair** [comment]
This could very well be a problem in the OAuth settings - maybe check with a [tracer extension](https://chromewebstore.google.com/detail/saml-ws-federation-and-oa/hkodokikbjolckghdnljbkbhacbhpnkb) if Microsft even returns data.
We are just consuming the upstream library so it is a bit difficult to debug without the exact setup in front of us. As a simpler test you can try adding GitHub as a SSO opton - that is a very simple provider and validates that the problem is not your setup per-se.

**Comment by belotv** [comment]
I think there is a real need to update the django-allauth library to a more recent version. The documentation for version 0.54 is not available anymore which makes SSO configuration a nightmare. I had similar configuration struggle for Keycloak as the openid_connect provider is not available in 0.54.

**Comment by diankov** [comment]
I believe [here](https://github.com/pennersr/django-allauth/blob/913092ebc20f0447accb322d1527ffca309d56df/docs/providers.rst#microsoft-graph) are the docs for Microsoft Graph at the time of version 0.54. But no clue there.

**Comment by SchrodingersGat** [comment]
Moving this to the next minor release - it may well require significant work to get this running smoothly

**Comment by SchrodingersGat** [comment]
@mittkkoo in https://github.com/inventree/InvenTree/pull/6099 I am adding in error logging so that the error message from microsoft is captured and logged to the database which should help here.

On the microsoft / azure side, have you created a separate client secret? This is different to the application ID and needs to be created separately

**Comment by SchrodingersGat** [comment]
@mittkkoo please LMK if the new patch fixes issues on your end

**Comment by mittkkoo** [comment]
> @mittkkoo please LMK if the new patch fixes issues on your end

I guess I will wait for 0.13.1 to appear in the master or stable branch on packager.io and the patch will be included. I assumed commits are automatically updated on packager.io at least on the master branch, but I can't find this one there. And I don't want to try to build from source, because I haven't done it before...

**Comment by mittkkoo** [comment]
OK, I updated to the latest version in the master branch on packager.io. Now the log patch does it job and here is the entry after an unsuccessful login attempt through Microsoft:

```
Error object (56)
[ИСТОРИЯ](https://lager.ageff.com/admin/error_report/error/56/history/)

Type:
OAuth2Error
Path:
/accounts/microsoft/login/callback/
Info:
Error retrieving access token: b'{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app \'1a331cbd-1d46-433xxxxx\'. Trace ID: f87402b2-c98d-40caxxxx Correlation ID: 4711a888-6175-4xxxxx Timestamp: 2024-01-12 19:11:47Z","error_codes":[7000215],"timestamp":"2024-01-12 19:11:47Z","trace_id":"f87402b2-cxxxxx","correlation_id":"4711a888-6175-xxxxx","error_uri":"https://login.microsoftonline.com/error?code=7000215"}'
When:
12 января 2024 г. 19:11
Data:
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 147, in dispatch
access_token = self.adapter.get_access_token_data(request, app, client)

File "/opt/inventree/env/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 70, in get_access_token_data
return client.get_access_token(code, pkce_code_verifier=pkce_code_verifier)

File "/opt/inventree/env/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/client.py", line 99, in get_access_token
raise OAuth2Error("Error retrieving access token: %s" % resp.content)

allauth.socialaccount.providers.oauth2.client.OAuth2Error: Error retrieving access token: b'{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app \'1a331cbd-1d46-43xxxx\'. Trace ID: f87402b2-c9xxxxx Correlation ID: 4711a888-6175-4xxxxx Timestamp: 2024-01-12 19:11:47Z","error_codes":[7000215],"timestamp":"2024-01-12 19:11:47Z","trace_id":"f87402b2-cxxxxx","correlation_id":"4711a888-617xxxx","error_uri":"https://login.microsoftonline.com/error?code=7000215"}'
```

**Comment by SchrodingersGat** [comment]
Sounds like you have the wrong values in the SSO configuration:

- https://learn.microsoft.com/en-us/answers/questions/1275176/invalid-client-secret-provided
- https://learn.microsoft.com/en-us/answers/questions/1000888/how-do-i-mitigate-aadsts7000215-invalid-client-sec

**Comment by mittkkoo** [comment]
It comes down to guess the corresponding entries. Here are the fields for allauth and what Microsoft offers
![inv](https://github.com/inventree/InvenTree/assets/76665232/b3cce634-6c99-4833-b2dd-27e4f4b59a92)

Microsoft also needs a Redirect URI:
![azur](https://github.com/inventree/InvenTree/assets/76665232/b93e4dcd-24c4-45a2-b9c2-a80e4d381196)


In addition there is the config.yaml in `/opt/inventree/InvenTree/config.yaml`
```
# Permit custom authentication backends
authentication_backends:
  - 'django.contrib.auth.backends.ModelBackend'
  - 'allauth.account.auth_backends.AuthenticationBackend'
#  Custom middleware, sometimes needed alongside an authentication backend change.
middleware:
  - 'django.middleware.security.SecurityMiddleware'
  - 'django.contrib.sessions.middleware.SessionMiddleware'
  - 'django.middleware.locale.LocaleMiddleware'
  - 'django.middleware.common.CommonMiddleware'
  - 'django.middleware.csrf.CsrfViewMiddleware'
  - 'corsheaders.middleware.CorsMiddleware'
  - 'django.contrib.auth.middleware.AuthenticationMiddleware'
  - 'django.contrib.messages.middleware.MessageMiddleware'
  - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  - 'InvenTree.middleware.AuthRequiredMiddleware'
  - 'allauth.account.middleware.AccountMiddleware'

# Add SSO login-backends (see examples below)
social_backends:
  - 'allauth.socialaccount.providers.microsoft'
#  - 'allauth.socialaccount.providers.github'
#  - 'allauth.socialaccount.providers.keycloak'

# Add specific settings for social account providers (if required)
# social_providers:
#   keycloak:
#     KEYCLOAK_URL: 'https://keycloak.custom/auth'
#     KEYCLOAK_REALM: 'master'
social_providers:
  microsoft:
    TENANT: organizations

```

My best guess, based on some posts on stackoverflow is:
**1C
2A
3B**

With this nothing is written in the error log. The Microsoft process is started but at the end Inventree reports _Sign up is currently closed._
Also I wonder about `TENANT: organizations`. Microsoft offers a value called _Directory (tenant) ID_. Can it really be that allauth won't need it...
