### ISSUE TITLE
[BUG] OIDC provider does not appear on login screen

### ISSUE THREAD

**Issue by WERTBON1789** [inventree/InvenTree#6037]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

It seems that the allauth openid_connect provider doesn't show up as a login option, but others (like microsoft) do

### Steps to Reproduce

configure social_backends in config.yaml:
```
social_backends:
  - 'allauth.socialaccount.providers.openid_connect'
  - 'allauth.socialaccount.providers.microsoft'
```

and even configure openid_connect, like this
```
social_providers:
  openid_connect:
    APPS: [
      {
        "provider_id": "authelia",
        "name": "Authelia",
        "client_id": "inventree",
        "secret": "<secret>",
        "settings": {
          "server_url": "https://sso.example.com"
        }
      }
    ]
```
or like this (not quite sure which if there is a problem in this config)
```
social_providers:
  openid_connect:
    APPS:
      - provider_id: authelia
        name: Authelia
        client_id: inventree
        secret: '<secret>'
        settings:
          server_url: https://sso.example.com
```

### Expected behaviour

The openid_connect provider should show up like the microsoft one does

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Docker: inventree/inventree:latest (pulled today)
Inventree: 0.13.0dev
Python: 3.10.13

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.
