### ISSUE TITLE
Deploy Inventree using docker without Caddy SSL

### ISSUE THREAD

**Issue by hillsandales** [inventree/InvenTree#7203]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I'm having trouble deploying the Inventree stack on my docker server. I only want to run the application internal to my network. Anything I want to expose publically is proxied with my router HAproxy configuration. I have managed to get the docker stack to run, but I cannot get web access to the stack, either by local IP:port or my domain name that I run through HAproxy.

At one point, I was getting errors in Chrome for too many redirects. The request was hitting the Caddy server, but the browser never showed the application. Something was pinging redirects back and forth.

Are there any suggestions on what to configure to make this work?

### Steps to Reproduce

Described above.

**Comment by hillsandales** [comment]
Tried a lot of things over the last few hours and managed to get to the site in a browser. I found that to get to Inventree through HAproxy, the INVENTREE_SITE_URL had to be set to `http://inventree.domain.tld`, not with **https://**, as I usually enter it in. https seems to have led to my problem with the Chrome TOO_MANY_REDIRECTS error. HAproxy is configured to redirect http to https, so maybe that has something to do with it?

However, while this is great, I'm still unable to get to the Inventree webapp using other URLs, such as by direct IP address to my server's IP. Sometimes this is useful when my DNS gets misconfigured... When I request `http://<serverIP>:8881`, or `http://<DNS_servername>:8881`, the browser returns a blank page. No error. Just a blank page. I see a request in the Caddy logs in Docker. The blank page, when looking at Inspect > Network, shows that favicon.ico is returned with 200 OK status. The browser tab icon changes to the Inventree icon. So the page isn't erroring out but just not returning what it should.  I only see activity in the Inventree Docker log when a request is sent to the same url as INVENTREE_SITE_URL, i.e. my external facing url of `https://inventree.domain.tld`.

I have set all these various combinations of URLs in `INVENTREE_TRUSTED_ORIGINS="url1,url2,..."`, `INVENTREE_CORS_ORIGIN_WHITELIST="url1,url2,..."`, and `INVENTREE_CORS_ORIGIN_ALLOW_ALL=true`, `INVENTREE_USE_X_FORWARDED_HOST=true`, `INVENTREE_USE_X_FORWARDED_PORT=false`.  The docs show that these list of URLs are lists, but doesn't show how the ENV VAR itself should represent these lists. Is the above correct? How are the USE_X_FORWARDED_ setting used? I'm able to set port, host, etc, for FORWARDED settings in my HAproxy instance, but I'm not sure what Inventree is expecting them to be set to. What am I missing? 

Thanks in advance for any guidance.

**Comment by SchrodingersGat** [comment]
If you want the InvenTree server to respond to the IP (in addition to the domain) then you will need to adjust the `Caddyfile` to listen on the IP address as well as the host.

So for example, change the section of your caddy file to something like:

![image](https://github.com/inventree/InvenTree/assets/10080325/0507376a-c5ad-45c5-a38e-4c560bd2e214)

Please note that the provided caddyfile is a starting point, which will work for a simple setup but does need some thinking if you are running behind another proxy.

**Comment by hillsandales** [comment]
Thanks for the response! Yes, I set my desired URLs here. I found I had to separate them by commas instead of spaces. Not sure if that makes a difference or not. I'm new to using Caddy. I also had to set the protocol to http:// instead of https://.

I also set INVENTREE_TRUSTED_ORIGINS and INVENTREE_CORS_ORIGIN_WHITELIST to a comma-separated list. I originally had quotation marks around the ENV VAR settings, but removed them as it was complaining it couldn't find it. Then it started working! Interestingly, for these variables, I had to set http:// for internal URLs and https:// for my HAproxy external URL.

Thank you for the help. Hopefully this thread helps someone else too!

**Comment by SchrodingersGat** [comment]
@hillsandales glad you got it working. If you feel that the documentation around this could be improved, please feel free so submit a pull request with some additional notes.

**Comment by yodaphone** [comment]
> Thanks for the response! Yes, I set my desired URLs here. I found I had to separate them by commas instead of spaces. Not sure if that makes a difference or not. I'm new to using Caddy. I also had to set the protocol to http:// instead of https://.
> 
> I also set INVENTREE_TRUSTED_ORIGINS and INVENTREE_CORS_ORIGIN_WHITELIST to a comma-separated list. I originally had quotation marks around the ENV VAR settings, but removed them as it was complaining it couldn't find it. Then it started working! Interestingly, for these variables, I had to set http:// for internal URLs and https:// for my HAproxy external URL.
> 
> Thank you for the help. Hopefully this thread helps someone else too!

I have the same issue as yours but splitting my hair over the configuration

will it be possible for you to share your redacted compose+env+Caddyfile ?

TIA

**Comment by hillsandales** [comment]
@yodaphone Sorry for the late reply. Here's my redacted config files that you requested.

> > Thanks for the response! Yes, I set my desired URLs here. I found I had to separate them by commas instead of spaces. Not sure if that makes a difference or not. I'm new to using Caddy. I also had to set the protocol to http:// instead of https://.
> > I also set INVENTREE_TRUSTED_ORIGINS and INVENTREE_CORS_ORIGIN_WHITELIST to a comma-separated list. I originally had quotation marks around the ENV VAR settings, but removed them as it was complaining it couldn't find it. Then it started working! Interestingly, for these variables, I had to set http:// for internal URLs and https:// for my HAproxy external URL.
> > Thank you for the help. Hopefully this thread helps someone else too!
> 
> I have the same issue as yours but splitting my hair over the configuration
> 
> will it be possible for you to share your redacted compose+env+Caddyfile ?
> 
> TIA

**docker-compose**
Stack environment configured using Portainer. I **did** change this docker-compose file, unlike what the original file indicates. From what I remember, it was mainly commenting out the sections I didn't need due to my own network configuration.

I did setup the Postgres server in the docker stack, but I'm not using it. I use an external MariaDB server for inventree on another host. However, from what I remember, if I commented out the Postgres server here, the container had problems starting.
```
version: "3.8"

# Docker compose recipe for a production-ready InvenTree setup, with the following containers:
# - PostgreSQL as the database backend
# - gunicorn as the InvenTree web server
# - django-q as the InvenTree background worker process
# - Caddy as a reverse proxy
# - redis as the cache manager (optional, disabled by default)

# ---------------------
# READ BEFORE STARTING!
# ---------------------

# -----------------------------
# Setting environment variables
# -----------------------------
# Shared environment variables should be stored in the .env file
# Changes made to this file are reflected across all containers!
#
# IMPORTANT NOTE:
# You should not have to change *anything* within this docker-compose.yml file!
# Instead, make any changes in the .env file!

# ------------------------
# InvenTree Image Versions
# ------------------------
# By default, this docker-compose script targets the STABLE version of InvenTree,
# image: inventree/inventree:stable
#
# To run the LATEST (development) version of InvenTree,
# change the INVENTREE_TAG variable (in the .env file) to "latest"
#
# Alternatively, you could target a specific tagged release version with (for example):
# INVENTREE_TAG=0.7.5
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    # only runs under the "redis" profile : https://docs.docker.com/compose/profiles/
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        depends_on:
            - inventree-db
        #profiles:
        #    - redis
        #env_file:
        #    - /srv/docker/inventree/stack.env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        #command: invoke update # Uncomment to update
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
        #env_file:
        #    - /srv/docker/inventree/stack.env
        environment:
            - INVENTREE_PLUGINS_ENABLED=${INVENTREE_PLUGINS_ENABLED}
            - INVENTREE_LOG_LEVEL=${INVENTREE_LOG_LEVEL}
            - INVENTREE_DB_LOGGING=${INVENTREE_DB_LOGGING}
            - INVENTREE_AUTO_UPDATE=${INVENTREE_AUTO_UPDATE}
            - INVENTREE_DEBUG=${INVENTREE_DEBUG}
            - INVENTREE_TIMEZONE=${INVENTREE_TIMEZONE}
            - INVENTREE_ALLOWED_HOSTS=${INVENTREE_ALLOWED_HOSTS}
            - INVENTREE_TRUSTED_ORIGINS=${INVENTREE_TRUSTED_ORIGINS}
            - INVENTREE_CORS_ORIGIN_WHITELIST=${INVENTREE_CORS_ORIGIN_WHITELIST}
            - INVENTREE_USE_X_FORWARDED_HOST=${INVENTREE_USE_X_FORWARDED_HOST}
            - INVENTREE_USE_X_FORWARDED_PORT=${INVENTREE_USE_X_FORWARDED_PORT}
            - INVENTREE_CORS_ORIGIN_ALLOW_ALL=${INVENTREE_CORS_ORIGIN_ALLOW_ALL}
            - INVENTREE_SITE_URL=${INVENTREE_SITE_URL}
            - INVENTREE_ADMIN_USER=${INVENTREE_ADMIN_USER}
            - INVENTREE_ADMIN_EMAIL=${INVENTREE_ADMIN_EMAIL}
            - INVENTREE_ADMIN_PASSWORD=${INVENTREE_ADMIN_PASSWORD}
            - INVENTREE_ADMIN_ENABLED=${INVENTREE_ADMIN_ENABLED}

        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        #env_file:
        #    - /srv/docker/inventree/stack.env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            #- 443:443
        #env_file:
        #    - /srv/docker/inventree/stack.env
        environment:
            #- INVENTREE_PLUGINS_ENABLED=${INVENTREE_PLUGINS_ENABLED}
            #- INVENTREE_LOG_LEVEL=${INVENTREE_LOG_LEVEL}
            #- INVENTREE_DB_LOGGING${INVENTREE_DB_LOGGING}
            #- INVENTREE_AUTO_UPDATE=${INVENTREE_AUTO_UPDATE}
            #- INVENTREE_DEBUG=${INVENTREE_DEBUG}
            #- INVENTREE_TIMEZONE=${INVENTREE_TIMEZONE}
            #- INVENTREE_ALLOWED_HOSTS=${INVENTREE_ALLOWED_HOSTS}
            - INVENTREE_SITE_URL=${INVENTREE_SITE_URL}
        volumes:
            - ${INVENTREE_EXT_VOLUME}/Caddyfile:/etc/caddy/Caddyfile:ro
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z
```

**Caddyfile** (redacted)
```
# Caddyfile for Inventree
# The following environment variables may be used:
# - INVENTREE_SITE_URL: The upstream URL of the Inventree site (default: inventree.localhost)
# - INVENTREE_SERVER: The internal URL of the Inventree container (default: http://inventree-server:8000)

# Global Options
#{
#       #auto_https off
#       auto_https disable_certs
#}

(log_common) {
        log {
                output file /var/log/caddy/{args[0]}.access.log
        }
}

(cors-headers) {
        header Allow GET,HEAD,OPTIONS
        header Access-Control-Allow-Origin *
        header Access-Control-Allow-Methods GET,HEAD,OPTIONS
        header Access-Control-Allow-Headers Authorization,Content-Type,User-Agent

        @cors_preflight{args[0]} method OPTIONS

        handle @cors_preflight{args[0]} {
                respond "" 204
        }
}

# Change the host to your domain (this will serve at inventree.localhost)
#{$INVENTREE_SITE_URL:inventree.localhost} {
#{$INVENTREE_SITE_URL} {
# Set this to the list of URLs that can reach InvenTree
http://<HOSTNAME1>, http://<HOSTNAME2, http://<HOST_IP> {
        import log_common inventree

        encode gzip

        request_body {
                max_size 100MB
        }

        handle_path /static/* {
                import cors-headers static

                root * /var/www/static
                file_server
        }

        handle_path /media/* {
                import cors-headers media

                root * /var/www/media
                file_server

                header Content-Disposition attachment

                forward_auth {$INVENTREE_SERVER:"http://inventree-server:8000"} {
                        uri /auth/
                }
        }

        reverse_proxy {$INVENTREE_SERVER:"http://inventree-server:8000"}
}
```

**environment file** (redacted)
```
INVENTREE_EXT_VOLUME=<path_to_external_volume>
INVENTREE_DEBUG=false
INVENTREE_LOG_LEVEL=DEBUG
INVENTREE_DB_LOGGING=true
INVENTREE_ADMIN_ENABLED=true
INVENTREE_ADMIN_USER=<inventree_admin_username>
INVENTREE_ADMIN_PASSWORD=<inventree_admin_password>
INVENTREE_ADMIN_EMAIL=<inventree_admin_email_seems_to_be_required>
INVENTREE_DB_ENGINE=mysql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=<database_server_hostname>
INVENTREE_DB_PORT=3306
INVENTREE_DB_USER=inventree
INVENTREE_DB_PASSWORD=<inventree_db_password>
INVENTREE_GUNICORN_TIMEOUT=90
INVENTREE_PLUGINS_ENABLED=true
INVENTREE_AUTO_UPDATE=true
INVENTREE_TAG=0.15.3
INVENTREE_SITE_URL=<inventree_site_url_reference_other_2_files_for_value>
INVENTREE_WEB_PORT=8881
INVENTREE_TIMEZONE=<timezone>
COMPOSE_PROJECT_NAME=inventree
INVENTREE_ALLOWED_HOSTS=*
INVENTREE_TRUSTED_ORIGINS=https://<host_url_1>,http://<docker_server_ip>,http://<host_url_2>
INVENTREE_CORS_ORIGIN_WHITELIST=https://<host_url_1>,http://<docker_server_ip>,http://<host_url_2>
INVENTREE_USE_X_FORWARDED_HOST=true
INVENTREE_USE_X_FORWARDED_PORT=true
INVENTREE_CORS_ORIGIN_ALLOW_ALL=true
INVENTREE_BACKUP_DIR=/srv/docker/inventree/backups
```

From what I remember, the host names was the tricky part for me. I run inventree in a docker stack, so I added that server's IP, the local DNS hostname, and an external DNS host name that runs through https. The external https:// endpoint runs through my firewall and is redirected to the docker server. The firewall uses HAproxy, which uses the firewall's cert that it itself pulls from Lets Encrypt. Hence I didn't need all the stuff for HTTPS that Inventree has built in.

Hope this helps!
