### ISSUE TITLE
Docker Deployment without Caddy SSL

### ISSUE THREAD

**Issue by yodaphone** [inventree/InvenTree#7303]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I already have a Caddy Reverse Proxy setup & want to use that. I looked at a similar post earlier but I'm unable to get Inventree up & running with Docker.

I have edited the Caddyfile & removed the reverse_proxy directive. this is my Caddyfile now. can you please let me know if i'm missing something here?

I have an entry for this on my caddy server 

```
inventree.foo.com {
    reverse_proxy   http://192.168.11.150
}
```

```
(log_common) {
        log {
                output file /var/log/caddy/{args[0]}.access.log
        }
}

(cors-headers) {
        header Allow GET,HEAD,OPTIONS
        header Access-Control-Allow-Origin *
        header Access-Control-Allow-Methods GET,HEAD,OPTIONS
        header Access-Control-Allow-Headers Authorization,Content-Type,User-Agent

        @cors_preflight{args[0]} method OPTIONS

        handle @cors_preflight{args[0]} {
                respond "" 204
        }
}

# Change the host to your domain (this will serve at inventree.localhost)
{$INVENTREE_SITE_URL:http://inventree.prakrithi.com, http://inventre.prakrithi.com, http://192.168.11.150} {
        import log_common inventree

        encode gzip

        request_body {
                max_size 100MB
        }

        handle_path /static/* {
                import cors-headers static

                root * /var/www/static
                file_server
        }

        handle_path /media/* {
                import cors-headers media

                root * /var/www/media
                file_server

                header Content-Disposition attachment

                forward_auth {$INVENTREE_SERVER:"http://inventree-server:8000"} {
                        uri /auth/
                }
        }

#       reverse_proxy {$INVENTREE_SERVER:"http://inventree-server:8000"}
}
```

The containers start without any errors

my docker compose file

```
services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    # only runs under the "redis" profile : https://docs.docker.com/compose/profiles/
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        depends_on:
            - inventree-db
        profiles:
            - redis
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: iarekylew00t/caddy-cloudflare:latest
        restart: always
        depends_on:
            - inventree-server
        ports:
            - 80:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z
```

My .env

```
# InvenTree environment variables for docker compose deployment

# Specify the location of the external data volume
# By default, placed in local directory 'inventree-data'
INVENTREE_EXT_VOLUME=./inventree-data

# Ensure debug is false for a production setup
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING

# InvenTree admin account details
# Un-comment (and complete) these lines to auto-create an admin acount
INVENTREE_ADMIN_USER=admin
INVENTREE_ADMIN_PASSWORD=admin123
INVENTREE_ADMIN_EMAIL=admin@foo.com

# Database configuration options
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432

# Database credentials - These should be changed from the default values!
INVENTREE_DB_USER=pguser
INVENTREE_DB_PASSWORD=somepassword

# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
#INVENTREE_CACHE_HOST=inventree-cache
#INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=True

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=True

# Image tag that should be used
INVENTREE_TAG=stable

# Site URL - update this to match your host
INVENTREE_SITE_URL="https://inventre.foo.com"

COMPOSE_PROJECT_NAME=inventree
INVENTREE_TRUSTED_ORIGINS=http://inventree.foo.com, http://inventre.foo.com
INVENTREE_CORS_ORIGIN_WHITELIST=http://inventree.foo.com, http://inventre.foo.com
```

### Steps to Reproduce

Using Inventree Docker & removed line 58 - reverse_proxy directive

### Relevant log output

```bash
docker compose up
[+] Running 5/5
 ✔ Network inventree_default   Created                                                                                                                                                                                                  0.1s
 ✔ Container inventree-db      Created                                                                                                                                                                                                  0.1s
 ✔ Container inventree-server  Created                                                                                                                                                                                                  0.1s
 ✔ Container inventree-proxy   Created                                                                                                                                                                                                  0.1s
 ✔ Container inventree-worker  Created                                                                                                                                                                                                  0.1s
Attaching to inventree-db, inventree-proxy, inventree-server, inventree-worker
inventree-db      |
inventree-db      | PostgreSQL Database directory appears to contain a database; Skipping initialization
inventree-db      |
inventree-db      | 2024-05-22 13:35:39.381 UTC [1] LOG:  starting PostgreSQL 13.15 (Debian 13.15-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
inventree-db      | 2024-05-22 13:35:39.381 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
inventree-db      | 2024-05-22 13:35:39.382 UTC [1] LOG:  listening on IPv6 address "::", port 5432
inventree-db      | 2024-05-22 13:35:39.394 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
inventree-db      | 2024-05-22 13:35:39.408 UTC [27] LOG:  database system was shut down at 2024-05-22 13:35:32 UTC
inventree-db      | 2024-05-22 13:35:39.417 UTC [1] LOG:  database system is ready to accept connections
inventree-server  | Loading config file : /home/inventree/data/config.yaml
inventree-worker  | Loading config file : /home/inventree/data/config.yaml
inventree-proxy   | {"level":"info","ts":1716384940.3283658,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
inventree-proxy   | {"level":"info","ts":1716384940.348395,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
inventree-proxy   | {"level":"info","ts":1716384940.3492358,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0002b6e00"}
inventree-proxy   | {"level":"warn","ts":1716384940.3492868,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
inventree-proxy   | {"level":"info","ts":1716384940.353501,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
inventree-proxy   | {"level":"info","ts":1716384940.3538268,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
inventree-proxy   | {"level":"info","ts":1716384940.3538432,"msg":"serving initial configuration"}
inventree-proxy   | {"level":"warn","ts":1716384940.3599265,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"f24cf1fc-0218-41c0-9021-8069cc8b9179","try_again":1716471340.3599231,"try_again_in":86399.99999886}
inventree-proxy   | {"level":"info","ts":1716384940.360374,"logger":"tls","msg":"finished cleaning storage units"}
inventree-server  | Python version 3.11.9 - /usr/local/bin/python
inventree-worker  | Python version 3.11.9 - /usr/local/bin/python3
inventree-worker  | /root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
inventree-worker  |   warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
inventree-worker  | Waiting for database...
inventree-worker  | Database connection successful!
inventree-server  | /root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
inventree-server  |   warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
inventree-worker  | Python version 3.11.9 - /usr/local/bin/python3
inventree-worker  | /root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
inventree-worker  |   warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
```
