### ISSUE TITLE
OpenID SSO provider not found

### ISSUE THREAD

**Issue by assada** [inventree/InvenTree#7892]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*
allauth documentation for keycloak: https://docs.allauth.org/en/latest/socialaccount/providers/keycloak.html

But:
`SSO SocialApp not found for provider 'openid_connect'` console error for OIDC provider 

Related to: https://github.com/inventree/InvenTree/issues/6037 https://github.com/inventree/InvenTree/discussions/5966

### Steps to Reproduce

my configuration: 

```yaml
social_backends:
  - 'allauth.socialaccount.providers.openid_connect'

social_providers:
    openid_connect:
        APPS: [
          {
            "provider_id": "keycloak",
            "name": "TestLogin",
            "client_id": "inventory",
            "secret": "<secret>",
            "settings": {
              "server_url": "https://<secret>/realms/master/.well-known/openid-configuration"
            }
          }
        ]
```

1. Go to https://<secret>/accounts/keycloak/login/?process=login
2. In Browser:
![image](https://github.com/user-attachments/assets/8b559929-4730-4fd3-947a-110a371fad05)
3. in console: `SSO SocialApp not found for provider 'openid_connect'`

### Expected behaviour

Redirected to openid provider

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

latest stable

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.
