### ISSUE TITLE
No idea what 'server' is!

### ISSUE THREAD

**Issue by Mattie112** [inventree/InvenTree#8705]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

We used to start our Inventree with a `invoke server` command as we needed to install the S3 storages module before launching.

(Kubernets yaml snippet)
```
      containers:
        - name: inventree-server
          image: inventree/inventree:stable
          envFrom:
            - configMapRef:
                name: inventree-config
          env:
            - name: "INVENTREE_DB_NAME"
              value: "inventree"
              [..]
          ports:
            - containerPort: 8000
          command: [ "/bin/sh", "-c" ]
          args: [ "pip install django-storages django-storages[boto3] && invoke server -a ${INVENTREE_WEB_ADDR}:${INVENTREE_WEB_PORT}" ]
          volumeMounts:
            - mountPath: /home/inventree/data
              name: inventree-data
            - mountPath: /var/www/static
              name: inventree-data
              subPath: static
```

However that now throws the error `No idea what 'server' is!. I can only assume that `server` has been changed to something else?

```
[..]
2024-12-18T14:09:00+01:00 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2024-12-18T14:09:01+01:00 No idea what 'server' is!
```

If I do an `invoke --list` I do see the following:

``` 
/home/inventree # invoke --list | grep server
  dev.docs-server                   Start a local mkdocs server to view the
  dev.frontend-server               Start frontend development server.
  dev.gunicorn                      Launch a gunicorn webserver.
  dev.server                        Launch a (development) server using
                                    Django's in-built webserver.
```
Do I now need to use `dev.server` ? Or Gunicorn?

I don't see anything listed at the breaking changes in the release notes: https://inventree.org/blog/2024/12/17/0.17.0
Also on https://github.com/inventree/InvenTree/releases/tag/0.17.0 I see nothing (relevant) about 'invoke' or 'server'

Please advise on what to use.

edit:
I use the `invoke server -a [..]` because I stole that command from the [Dockerfile](https://github.com/inventree/InvenTree/blob/master/contrib/container/Dockerfile). Which still seem to be that command perhaps that is now also wrong? 

### Steps to Reproduce

See above

### Expected behaviour

See above

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [x] Other - added info in Steps to Reproduce

### Version Information

0.17.0

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by Mattie112** [comment]
Thanks,
I do run the proxy:

```
        - name: inventree-proxy
          image: nginx:stable
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
              name: nginx-config
              readOnly: true
            - mountPath: /var/www
              name: inventree-data
          readinessProbe:
            httpGet:
              path: /health/
              port: 8080
            periodSeconds: 3
 ```

I will give the `dev.gunicorn` a shot. So that is recommended even though it is listed under `dev.` ?
