### ISSUE TITLE
Docker Compose - Database "inventree" does not exist

### ISSUE THREAD

**Issue by Kampi** [inventree/InvenTree#8967]
### Deployment Method

- [ ] Installer
- [x] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I try to run InvenTree with Docker on my NAS with the following configuration:

```
version: "3.9"
services:
    InvenTree_Postgres:
        image: postgres:13
        container_name: InvenTree-Postgres
        restart: always
        environment:
            - PGDATA=./db
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=5432
        volumes:
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z

    InvenTree_Cache:
        image: redis:7.0
        container_name: InvenTree-Cache
        restart: always
        depends_on:
            - InvenTree_Postgres
        profiles:
            - redis
        env_file:
            - .env

    InvenTree_Server:
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: InvenTree-Server
        restart: always
        ports:
            - 9753:8000
        depends_on:
            - InvenTree_Postgres
        env_file:
            - .env
        volumes:
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z

    InvenTree_Worker:
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: IncenTree-Worker
        restart: always
        command: invoke worker
        depends_on:
            - InvenTree_Server
        env_file:
            - .env
        volumes:
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z`
```

But the container `InvenTree_Postgres` shows an error that the database `inventree` does not exist.

![Image](https://github.com/user-attachments/assets/43e6a014-c353-4211-bbbf-7c517243ea13)

Do you know how I can fix this error?

### Steps to Reproduce

See docker-compose.yml

### Relevant log output

```bash

```

**Comment by SchrodingersGat** [comment]
Yes, you have not correctly specified the database name in your postgres container:


```yaml
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped
```

Note that `POSTGRES_DB` is the *name* of the database ("inventree" by default, as per the `INVENTREE_DB_NAME` in our standard `.env` file). You have specified `5432` which is a port number.
