### ISSUE TITLE
Can not print label from Docker Container

### ISSUE THREAD

**Issue by Kampi** [inventree/InvenTree#8988]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I try to print a label from a part

![Image](https://github.com/user-attachments/assets/32df9f87-e51d-475c-ac7a-e30c2d04f344)

and nothing happens. Instead, I get redirected to this page

![Image](https://github.com/user-attachments/assets/9810dd53-71e7-4a2e-ae23-754e1b7ddaa3)

### Steps to Reproduce

See description

### Expected behaviour

A printed label as PDF

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.4
Django Version: 4.2.17
Commit Hash: de431b8
Commit Date: 2025-01-28

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.4.302+-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by Kampi** [comment]
No, I don´t see any error. Please take a look at the server log (HTML file).

[InvenTree-Server.txt](https://github.com/user-attachments/files/18608901/InvenTree-Server.txt)

**Comment by SchrodingersGat** [comment]
Please also provide any output from the developer console in your browser - there is likely an error message as you press the button.

**Comment by gpetrom** [comment]
I can confirm that behavior. I did not noticed any errors in developer console. It redirects to index page

**Comment by SchrodingersGat** [comment]
You can use the "preserve logs" in the developer console to view the network events before the redirect

**Comment by gpetrom** [comment]
Also with preserve logs i am not seeing any errors in developer console

**Comment by SchrodingersGat** [comment]
Can you please try with the new user interface? You can access at `/platform/` URL relative to your inventree server. Let me know if the problem persists in the new UI

**Comment by gpetrom** [comment]
Yes i have tried and with the new interface same thing happens and redirects to sample.com/index

**Comment by gpetrom** [comment]
I think i found what is causing the problem. When INVENTREE_DEBUG = False it does not print the labels when it is True it is working.

**Comment by Kampi** [comment]
> I think i found what is causing the problem. When INVENTREE_DEBUG = False it does not print the labels when it is True it is working.

This doesn´t work for me.

@SchrodingersGat: Where can I find the developer console? The new UI doesn´t load for me so I can´t test it.

**Comment by gpetrom** [comment]
@Kampi where do you change this? 
I have an .env file and there i have all environment variables when i start the container. In this file i have changed INVENTREE_DEBUG
You mast stop and the start the container for this to work

**Comment by gpetrom** [comment]
@matmair The instance i have right now is a test environment just to check the program. 
Do you have any ideas what is causing the problem when inventree it not on debug mode ?

**Comment by SchrodingersGat** [comment]
@gpetrom  are you using *our* docker-compose setup, or a custom one?

**Comment by gpetrom** [comment]
@SchrodingersGat  Here is the docker-compose file that i am using
```
services:
  inventree:
    image: inventree/inventree:stable
    container_name: inventree
    env_file:
      - .env
    ports:
      - "8283:${INVENTREE_PORT}"
    volumes:
      - ./data:/home/inventree/data
    depends_on:
      - inventree-cache
    restart: unless-stopped

  inventree-cache:
    image: redis:alpine
    container_name: inventree-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    image: inventree/inventree:stable
    container_name: inventree_worker
    command: invoke worker  # This runs the Celery worker
    env_file:
      - .env
    volumes:
      - ./data:/home/inventree/data
    restart: unless-stopped
    depends_on:
      - inventree
      - inventree-cache
volumes:
  inventree_data:
```
