### ISSUE TITLE
Can not upload an image in bare metal install

### ISSUE THREAD

**Issue by mikelemo** [inventree/InvenTree#9263]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Just installed bare metal inventree and after configuring '~/data/media' directory settimg / updaloading pictures to parts dont work.

I've got this set in "~/src/config.yml" along with env variables like `INVENTREE_MDEIA_ROOT` with `export`:

```yml
# MEDIA_ROOT is the local filesystem location for storing uploaded fi>
media_root: '/home/inventree/data/media'

# STATIC_ROOT is the local filesystem location for storing static fil>
static_root: '/home/inventree/data/static'

# INVENTREE_BACKUP_DIR is the local filesystem location for storing b>
backup_dir: '/home/inventree/data/backup'

```

But no luck, any idea why?

### Steps to Reproduce

Go to http://localhost:8000/platform/part/2/details
upload an image by dragging or with file dialog

### Expected behaviour

get disappointed and figure file/image uploading doesn't work.

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.18.0 dev
Django Version: 4.2.19
Commit Hash: 06961c6
Commit Date: 2025-03-07
Commit Branch: master
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.11.0-17-generic-x86_64-with-glibc2.39
Installer: GIT
Active plugins: false

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```
