### ISSUE TITLE
Random error when calling a view function via a button in template

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#9363]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Sorry for the long ticket. This it a bit tricky. I started a plugin using the new UserInterfaceMixin. The target is to call a python function when a button is clicked. I boild the example down to them minimum:

```
from django.urls import re_path
from django.http import HttpResponse
from plugin import InvenTreePlugin
from plugin.mixins import UserInterfaceMixin, UrlsMixin


class SampleUserInterfacePlugin(UserInterfaceMixin, InvenTreePlugin, UrlsMixin):

    NAME = 'TestPlugin'
    SLUG = 'testplugin'
    TITLE = 'User Interface Plugin'
    DESCRIPTION = 'A test plugin'

    def get_ui_panels(self, request, context, **kwargs):
        panels = []
        context = context or {}
        print('## Init panels')
        self.mydata = "This is a test"
        target_model = context.get('target_model', None)
        if target_model == 'purchaseorder':
            panels.append({
                'key': 'purchase_order_panel',
                'title': 'Purchase Order Panel',
                'source': self.plugin_static_file('sample_panel.js:renderPoPanel'),
            })
        return panels

    def setup_urls(self):
        return [re_path(r'bocompanyselect/', self.process_data, name='transfer')]

    def process_data(self, request):
        print('process data')
        print(self.mydata)
        return HttpResponse('OK')
```

I use the following javascript for the panel:

```
export function renderPoPanel(target, data) {
    if (!target) {
        console.error("No target provided to renderPoPanel");
        return;
    }

    target.innerHTML = `
    <p>This is a test panel</p>
    <button type='button' id='button1' >Add</button>
    `;

    button1.onclick = function(){
        var response = fetch("http://inventree.localhost/plugin/testplugin/bocompanyselect/");
    }
}
```

This works fine in a bare metal environment using the django web server.  However when I switch to container latest I  sometimes get the following error

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/data/plugins/user_interface_sample.py", line 34, in process_data
    print(self.mydata)
          ^^^^^^    """A sample plugin which demonstrates user interface integrations."""
^^^^^
AttributeError: 'SampleUserInterfacePlugin' object has no attribute 'mydata'
2025-03-23 18:18:04,545 ERROR {'code': 500, 'request': 'GET /plugin/testplugin/bocompanyselect/', 'event': 'request_failed', 'user_id': 136, 'request_id': 'd0536f51-f340-4675-8bc5-3fcd71205d4f', 'ip': '172.18.0.1', 'timestamp': '2025-03-23T18:18:04.544787Z', 'logger': 'django_structlog.middlewares.request', 'level': 'error', 'exception': 'Traceback (most recent call last):\n  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/inventree/data/plugins/user_interface_sample.py", line 34, in process_data\n    print(self.mydata)\n          ^^^^^^^^^^^\nAttributeError: \'SampleUserInterfacePlugin\' object has no attribute \'mydata\''}
2025-03-23 18:18:04,547 ERROR Internal Server Error: /plugin/testplugin/bocompanyselect/
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/data/plugins/user_interface_sample.py", line 34, in process_data
    print(self.mydata)
          ^^^^^^^^^^^
AttributeError: 'SampleUserInterfacePlugin' object has no attribute 'mydata'
```

It seems the variable mydata defined in the beginning is not there any longer. 
This error does not always show up. After several refresh, or changing to another page and coming back it might work. Or not...
I see the same problem in CUI on 0.17.0 using the old PanelMixin. 
What am I doing wrong?

### Steps to Reproduce

docker_compose.yml
```
services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
            - inventree-cache
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z

    # alternative: run nginx as reverse proxy
    #inventree-proxy:
    #    container_name: inventree-proxy
    #    image: nginx:stable
    #    restart: always
    #    depends_on:
    #        - inventree-server
    #    ports:
    #        - ${INVENTREE_WEB_PORT:-80}:80
    #        - 443:443
    #    volumes:
    #        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
    #        - ${INVENTREE_EXT_VOLUME}:/var/www:z
```
.env

```
# InvenTree environment variables for docker compose deployment
# For a full list of the available configuration options, refer to the InvenTree documentation:
# https://docs.inventree.org/en/stable/start/config/

# Specify the name of the docker-compose project
COMPOSE_PROJECT_NAME=inventree

# InvenTree version tag (e.g. 'stable' / 'latest' / 'x.x.x')
INVENTREE_TAG=latest

# InvenTree server URL - update this to match your host
# INVENTREE_SITE_URL="http://192.168.1.40"
INVENTREE_SITE_URL="http://inventree.localhost"

# Specify the location of the external data volume
# By default, placed in local directory 'inventree-data'
INVENTREE_EXT_VOLUME=./inventree-data

# Ensure debug is false for a production setup
INVENTREE_LOG_LEVEL=WARNING

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=True

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=True

# InvenTree superuser account details
# Un-comment (and complete) these lines to auto-create an admin acount
INVENTREE_ADMIN_USER=michael
INVENTREE_ADMIN_PASSWORD=tomate77
INVENTREE_ADMIN_EMAIL=michael@bla.blu

# Database configuration options
# DO NOT CHANGE THESE SETTINGS (unless you really know what you are doing)
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree_new
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432

# Database credentials - These should be changed from the default values!
# Note: These are *NOT* the InvenTree server login credentials,
#       they are the credentials for the PostgreSQL database
INVENTREE_DB_USER=pguser
INVENTREE_DB_PASSWORD=pgpassword

# Redis cache setup
# Refer to the documentation for other cache options
INVENTREE_CACHE_ENABLED=True
INVENTREE_CACHE_HOST=inventree-cache
INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90
``


### Expected behaviour

process_data should always print

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

docker latest
caddy



### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
see description
```
