### ISSUE TITLE
Docker install with cloudflare proxy serves no content.

### ISSUE THREAD

**Issue by salem-ggit** [inventree/InvenTree#9883]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [x] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Attempting to run Inventree accessible through a CF hosted domain, using the cloudflare proxy and tunnel.

I am able to connect to inventree without issue at the local IP 192.168.1.201, but when attempting to connect to "http://inventree.mydomain.com" i receive a blank page with no content. Checking inspector network tab shows this:
![Image](https://github.com/user-attachments/assets/a1cee7f5-8f6e-47fc-bbc7-9f3d8ee59590)

### Steps to Reproduce

1. Pull inventree:stable and config files from docker production install guide.
2. Edited .env variables:
- INVENTREE_SITE_URL="192.168.1.201"
- INVENTREE_WEB_PORT=7080
- INVENTREE_SSL_PORT=7443 (added env variable to inventree-proxy:443)
- INVENTREE_ALLOWED_HOSTS=".mydomain.com"
- INVENTREE_TRUSTED_ORIGINS="https://*.mydomain.com,http://*.mydomain.com"
3. Edited docker-compose: [docker-compose.yml_inv_edit.txt](https://github.com/user-attachments/files/20954296/docker-compose.yml_inv_edit.txt)
- explicitly name default network as "inventree-default"
- add env variable for inventree-proxy:443
4. Continue w/ typical install, invoke update, invoke superuser, compose up.

### Relevant log output

```bash
Connecting to "http://inventree.mydomain.com":
inventree-proxy   | {"level":"info","ts":1750976175.1171386,"logger":"http.log.access","msg":"NOP","request":{"remote_ip":"192.168.1.201","remote_port":"42344","client_ip":"192.168.1.201","proto":"HTTP/1.1","method":"GET","host":"inventree.mydomain.com","uri":"/","headers":{"Cookie":["REDACTED"],"Sec-Ch-Ua":["\"Chromium\";v=\"136\", \"Google Chrome\";v=\"136\", \"Not.A/Brand\";v=\"99\""],"Cache-Control":["max-age=0"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Accept-Encoding":["gzip, br"],"Accept-Language":["en-US,en;q=0.9"],"Priority":["u=0, i"],"X-Forwarded-Proto":["https"],"Cf-Ray":["xxxxxxxxx-xxx"],"Sec-Fetch-Site":["none"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"],"Cf-Ipcountry":["US"],"Cf-Connecting-Ip":["xx.xx.xx.xx"],"Sec-Fetch-Dest":["document"],"Cdn-Loop":["cloudflare; loops=1"],"Cf-Warp-Tag-Id":["xxxxxxxxxx-xxxxxx-xxxx-xxxxxxxxxxxx"],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Connection":["keep-alive"],"X-Forwarded-For":["71.12.37.29"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Upgrade-Insecure-Requests":["1"]}},"bytes_read":0,"user_id":"","duration":0.000006145,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}

Connecting to 192.168.1.201:
inventree-server  | 192.168.1.201 - - [26/Jun/2025:22:11:48 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"

inventree-server  | 192.168.1.201 - - [26/Jun/2025:22:13:01 +0000] "GET /index/ HTTP/1.1" 200 23462 "http://192.168.1.201:7080/accounts/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
```

**Comment by SchrodingersGat** [comment]
> Edited docker-compose:

Please share your edited file!

**Comment by gitbock** [comment]
I am running a CF zero trust with inventree successfully. 
Can reach it from internal private ip (http) and external domain (CF https). 

ℹ️ **Info:** 
> Only thing that is not working is the app: It does not know how to interpret the CF auth site (Azure Entra ID SSO) and throws an error. Workaround is using WARP client.

Tricky part for me was the CORS trusted origin setup.


My .env file

```
INVENTREE_SITE_URL="http://inventree.mydomain.de"  
INVENTREE_TRUSTED_ORIGINS=https://inventree.mydomain.de,http://localhost,http://192.168.1.1,http://inventree.mydomain.de

```

<details>
  <summary>docker-compose.yml (nothing special here)</summary>

```
services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
            - inventree-cache
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z

```
  
</details>




CF App Setup

![Image](https://github.com/user-attachments/assets/75c56b41-4edd-4a84-8bdc-dbdad9765912)

![Image](https://github.com/user-attachments/assets/85407eb2-2fde-493f-921e-09a166fae912)

![Image](https://github.com/user-attachments/assets/b5e63d54-be2d-43a0-96ba-ed05a098216c)

As you can see, I am using only http to the backend, no https.


Hints:
1. Check Browser console for CORS errors (not network tab)
2. Check `docker logs <caddy_container_id> | <inventree_container_id>`after your web request

**Comment by greengarbology-it** [comment]
> > Edited docker-compose:
> 
> Please share your edited file!

[docker-compose.yml_inv_edit.txt](https://github.com/user-attachments/files/20954296/docker-compose.yml_inv_edit.txt)

<details>
<summary>Compose file</summary>
<br>

```
# Docker compose recipe for a production-ready InvenTree setup, with the following containers:
# - PostgreSQL as the database backend
# - gunicorn as the InvenTree web server
# - django-q as the InvenTree background worker process
# - Caddy as a reverse proxy
# - redis as the cache manager (optional, disabled by default)

# ---------------------
# READ BEFORE STARTING!
# ---------------------

# -----------------------------
# Setting environment variables
# -----------------------------
# Shared environment variables should be stored in the .env file
# Changes made to this file are reflected across all containers!
#
# IMPORTANT NOTE:
# You should not have to change *anything* within this docker-compose.yml file!
# Instead, make any changes in the .env file!

# ------------------------
# InvenTree Image Versions
# ------------------------
# By default, this docker-compose script targets the STABLE version of InvenTree,
# image: inventree/inventree:stable
#
# To run the LATEST (development) version of InvenTree,
# change the INVENTREE_TAG variable (in the .env file) to "latest"
#
# Alternatively, you could target a specific tagged release version with (for example):
# INVENTREE_TAG=0.7.5
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    inventree-db:
        image: postgres:13
        container_name: inventree-db
        expose:
            - ${INVENTREE_DB_PORT:-5432}/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
        restart: unless-stopped

    # redis acts as database cache manager
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        env_file:
            - .env
        expose:
            - ${INVENTREE_CACHE_PORT:-6379}
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    inventree-server:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        # Only change this port if you understand the stack.
        expose:
            - 8000
        depends_on:
            - inventree-db
            - inventree-cache
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    inventree-proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - inventree-server
        ports:
            - ${INVENTREE_WEB_PORT:-80}:80
            - ${INVENTREE_SSL_PORT:-443}:443
        env_file:
            - .env
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z
            -             - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z

    # alternative: run nginx as reverse proxy
    # inventree-proxy:
    #     container_name: inventree-proxy
    #     image: nginx:stable
    #     restart: always
    #     depends_on:
    #         - inventree-server
    #     ports:
    #         - ${INVENTREE_WEB_PORT:-80}:80
    #         - 443:443
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
    #         - ${INVENTREE_EXT_VOLUME}:/var/www:z

networks:
  default:
    name: inventree-default
```

</details>
